/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface FaTag {
      'icon': string;
      'text': string;
    }
  }

  interface HTMLFaTagElement extends StencilComponents.FaTag, HTMLStencilElement {}

  var HTMLFaTagElement: {
    prototype: HTMLFaTagElement;
    new (): HTMLFaTagElement;
  };
  interface HTMLElementTagNameMap {
    'fa-tag': HTMLFaTagElement;
  }
  interface ElementTagNameMap {
    'fa-tag': HTMLFaTagElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'fa-tag': JSXElements.FaTagAttributes;
    }
  }
  namespace JSXElements {
    export interface FaTagAttributes extends HTMLAttributes {
      'icon'?: string;
      'text'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;